# create a webserver and transfer the Docker image to Docker Hub
name: Nginx in docker image 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-container:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true 
        tags: ruyoliv/pr:nginx
