# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-container:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME2 }}
        password: ${{ secrets.DOCKER_PASSWORD2 }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true 
        tags: ruyoliv/pr:nginx

   # - name: Build the Docker image # push The image to the docker hub
   #   run: docker build . --file Dockerfile --tag ruyoliv/imagem_exemplo/nginx:latest
   # - name: Docker Push
   #   run: docker push $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
